CREATE TABLE IF NOT EXISTS games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS answers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  game_id INT NOT NULL,
  category VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  answer_id INT NOT NULL,
  question TEXT NOT NULL,
  difficulty INT NOT NULL,
  FOREIGN KEY (answer_id) REFERENCES answers(id)
);

CREATE TABLE IF NOT EXISTS migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL UNIQUE,
  run_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);